### ISSUE TITLE
Data paper

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/dbfc-dataset#12]
#### Description
Data paper draft

**Comment by sepandhaghighi** [comment]
@kasraaskari @sarminh 
Please consider that we need data paper abstract to close #11

**Comment by sarminh** [comment]
Abstract: 
Dataset includes Direct Borohydride Fuel Cell (DBFC) impedance and polarization test in anode with Pd/C, Pt/C and Acta catalysts. In fact, different concentration of Sodium Borohydride (SBH), applied voltages and various anode catalysts loading with explanation of experimental details of electrochemical analysis are considered in data. Voltage, power density and resistance of DBFC change as a function of weight percent of SBH (%), applied voltage and amount of anode catalyst loading that are evaluated by polarization and impedance curves with using appropriate equivalent circuit of fuel cell. Can be stated that interpretation of electrochemical behavior changes by the data of related cell is inevitable, which can be useful in simulation, power source investigation and depth analysis in DB fuel cell researches. 
@sepandhaghighi @kasraaskari
