### ISSUE TITLE
Acta Catalyst name

### ISSUE THREAD

**Issue by kasraaskari** [ECSIM/dbfc-dataset#15]
@sadrasabouri 
Change the name of **acta catalyst** to  **Pd decorated Ni–Co/rGO** everywhere in dataset

@sarminh 
Consider this issue for datapaper

**Comment by sadrasabouri** [comment]
<b>Pd decorated Ni–Co/rGO‍ Catalyst</b> right?

**Comment by kasraaskari** [comment]
> Pd decorated Ni–Co/rGO‍ Catalyst right?

yes, exactly right.
Pd stands for **Palladium**
Ni stands for **Nickel**
Co stands for **Cobalt**
rGO stands for **reduced graphene oxide**

**Comment by sadrasabouri** [comment]
There is just another point the `/` will cause some problems (It can be misunderstood by directory splitter) can we use another character like `_` or `-`?

**Comment by kasraaskari** [comment]
> There is just another point the `/` will cause some problems (It can be misunderstood by directory splitter) can we use another character like `_` or `-`?

Let me check it, because '/' has a specific meaning in chemical compounds.

**Comment by sadrasabouri** [comment]
@sepandhaghighi If there is a way for naming a directory with `/`, I'll be thankful if you help me with this.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi If there is a way for naming a directory with `/`, I'll be thankful if you help me with this.

It's not a good approach, because it may cause some problems in different environments.
I suggest to replace `/` by `-` **only in folder names**, like **Pd-C** and **Pt-C**

**Comment by kasraaskari** [comment]
> There is just another point the `/` will cause some problems (It can be misunderstood by directory splitter) can we use another character like `_` or `-`?

You can use '_'.
