### ISSUE TITLE
Add notebooks

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/dbfc-dataset#2]
#### Description
Add Jupyter notebook files

**Comment by sepandhaghighi** [comment]
@sadrasabouri Hi

Consider the following : 

1. Follow exactly the **same pattern** as [pem-dataset1](https://github.com/ECSIM/pem-dataset1) notebooks
2. I think you need only 2 functions (`impedance_plot` and `polarization_plot`)
3. Don't forget `requirements.txt`, `test.py` and `README.md`
4. I activated `travis` and `appveyor` for this project

Good luck ;-)

**Comment by sadrasabouri** [comment]
Thank you for your comments.
I'll handle it ASAP.
